name: keyword-releaser

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: iniguezfelix/GitHub_Actions@main
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        args: 'FIXED'
